# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=50)),
                ('deploy_type', models.CharField(choices=[('DEPLOY', 'deploy'), ('RESTART', 'restart'), ('ROLLBACK', 'rollback'), ('CANCEL', 'cancel')], default='DEPLOY', max_length=20)),
                ('deploy_retry', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('DEPLOY_READY', 'deploy_ready'), ('PRE_CHECK_FAIL', 'pre_check_fail'), ('DEPLOY_DONE', 'deploy_done'), ('DEPLOY_FAIL', 'deploy_fail'), ('POST_CHECK_FAIL', 'post_check_fail'), ('SUCCESS', 'success'), ('FAIL', 'fail')], default='NEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DeployHost',
                'verbose_name_plural': 'DeployHost',
            },
        ),
        migrations.CreateModel(
            name='DeployRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_form_id', models.CharField(max_length=50, unique=True)),
                ('product', models.CharField(max_length=50, null=True)),
                ('system', models.CharField(max_length=50, null=True)),
                ('app', models.CharField(max_length=50, null=True)),
                ('module', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('conn', models.IntegerField(default=1)),
                ('pre_script', models.CharField(max_length=250, null=True)),
                ('post_script', models.CharField(max_length=250, null=True)),
                ('deploy_tag', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DeployRequest',
                'verbose_name_plural': 'DeployRequest',
            },
        ),
        migrations.AddField(
            model_name='deployhost',
            name='deploy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DeployRequest'),
        ),
    ]
