# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployhost',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('DEPLOY_READY', 'deploy_ready'), ('PRE_CHECK_FAIL', 'pre_check_fail'), ('DEPLOY_DONE', 'deploy_done'), ('DEPLOY_FAIL', 'deploy_fail'), ('POST_CHECK_FAIL', 'post_check_fail'), ('SUCCESS', 'success'), ('FAIL', 'fail'), ('CANCEL', 'cancel')], default='NEW', max_length=30),
        ),
    ]
